version: '3.8'

services:
  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis-data:/data

  ml-service:
    build: ./ml-service
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ML_DATA_DIR=/data
      - SENTENCE_MODEL=all-MiniLM-L6-v2
      - RATE_LIMIT_PER_MIN=60
    ports:
      - "8001:8000"
    depends_on:
      - redis
    volumes:
      - ml-data:/data

  ml-worker:
    build: ./worker
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ML_DATA_DIR=/data
      - SENTENCE_MODEL=all-MiniLM-L6-v2
    depends_on:
      - redis
    volumes:
      - ml-data:/data

  ml-learner:
    build: ./worker
    restart: unless-stopped
    command: ["python","learner.py"]
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ML_DATA_DIR=/data
      - SENTENCE_MODEL=all-MiniLM-L6-v2
      - CLUSTER_SIM_THRESHOLD=0.75
    depends_on:
      - redis
    volumes:
      - ml-data:/data

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - ml-service

volumes:
  redis-data:
  ml-data:
